source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
workspace 'Circle'
xcodeproj 'Circle.xcodeproj'
pod 'AFNetworking', '~> 2.5'
pod 'Parse', '~> 1.5'
pod 'MGSwipeTableCell', '~> 1.3'
