source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
link_with 'Circle', 'CircleTests'
workspace 'Circle'
xcodeproj 'Circle.xcodeproj'
use_frameworks!

pod 'AFNetworking', '~> 2.5'
pod 'google-plus-ios-sdk', '~> 1.7'
pod 'libPhoneNumber-iOS', '~> 0.7'
pod 'Mixpanel', '~> 2.7'
pod 'PureLayout', '~> 2.0'
pod 'UIViewPlusPosition', '~> 0.0'
pod 'VENTouchLock', '~> 1.0'
pod 'AMScrollingNavbar', '~> 1.3'
pod 'Alamofire', '~> 1.2'
pod 'Locksmith', '~> 1.2'
