source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
workspace 'Circle'
xcodeproj 'Circle.xcodeproj'
pod 'AFNetworking', '~> 2.5'
pod 'MGSwipeTableCell', '~> 1.3'
pod 'Parse', '~> 1.5'
pod 'PureLayout', '~> 2.0.3'
pod 'SlackTextViewController', '~> 1.3.3'
pod 'PureLayout', '~> 2.0'
pod 'UIViewPlusPosition', '~> 0.0'
